AllCops:
  TargetRubyVersion: 2.3

AllCops:
  Exclude:
    - bin/**/*

# Disables "Use nested module/class definitions instead of compact style" warning
ClassAndModuleChildren:
  Enabled: false

# Increases "Class definition is too long" warning from 100 to 200
Metrics/ClassLength:
  Max: 200

# Increases "Module has too many lines" warning from 100 to 200
Metrics/ModuleLength:
  Max: 200

# Increases "Assignment Branch Condition size" warning from 15 to 30
Metrics/AbcSize:
  Max: 50

# Disables "Missing top-level class documentation comment" warning
Documentation:
  Enabled: false

# Disables "Line is too long" warning
LineLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false
  
PerceivedComplexity:
  Enabled: false

# Disables "Method has too many lines" warning
MethodLength:
  Enabled: false

Style/Encoding:
  Enabled: false

Layout:
  Enabled: False



#Metrics/MethodLength:
#  Exclude:
#    - 'Klass#method_with_large_hash'

#Metrics/LineLength:
#  Max: 120


